security:
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        # On définit comment Symfony doit aller chercher tes utilisateurs en base de données
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_profiler|_wdt|assets|build)/
            security: false
        main:
            lazy: true
            provider: app_user_provider # On lie le firewall à notre base de données

            # On active le système de connexion par formulaire
            form_login:
                login_path: app_login    # Nom de la route de ta page de connexion
                check_path: app_login    # Route qui vérifie les identifiants
                enable_csrf: true       # Sécurité contre les attaques CSRF

            # On active la déconnexion
            logout:
                path: app_logout
                # where to redirect after logout
                # target: app_any_route

            # Pour se souvenir de l'utilisateur (optionnel)
            # remember_me:
            #     secret:   '%kernel.secret%'
            #     lifetime: 604800 # 1 week
            #     path:     /

    # Contrôle d'accès (ex: réserver l'admin aux admins)
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/editor, roles: ROLE_EDITOR }
        - { path: ^/author, roles: ROLE_AUTHOR}
        - { path: ^/profile, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Valeur basse pour accélérer les tests
                time_cost: 3
                memory_cost: 10